describe('Sign Up Test', () => {
  beforeEach(() => {
    cy.visit('https://magento.softwaretestingboard.com/customer/account/create/.')
  })
  it('Failed Sign Up - Existing email', () => {
    cy.get('#firstname').type('Kelompok')
    cy.get('#lastname').type('Dua')
    cy.get('#email_address').type('kelompok2@mail.com')
    cy.get('#password').type('Kelompok2')
    cy.get('#password-confirmation').type('Kelompok2')
    cy.get("button[title='Create an Account']").click()
    cy.get('.message-error > div').should('contain','There is already an account with this email address. If you are sure that it is your email address, click here to get your password and access your account.')
  })
  it('Failed Sign Up - Invalid email', () => {
    cy.get('#firstname').type('Kelompok')
    cy.get('#lastname').type('Dua')
    cy.get('#email_address').type('kelompokdua')
    cy.get('#password').type('Kelompok2')
    cy.get('#password-confirmation').type('Kelompok2')
    cy.get("button[title='Create an Account']").click()
    cy.get('#email_address-error').should('contain','Please enter a valid email address (Ex: johndoe@domain.com).')
  })
  it('Failed Sign Up - Password too short', () => {
    cy.get('#firstname').type('Kelompok')
    cy.get('#lastname').type('Dua')
    cy.get('#email_address').type('kelompok2@mail.com')
    cy.get('#password').type('12345')
    cy.get('#password-confirmation').type('12345')
    cy.get("button[title='Create an Account']").click()
    cy.get('#password-error').should('contain','Minimum length of this field must be equal or greater than 8 symbols. Leading and trailing spaces will be ignored.')
})
    it('Failed Sign Up - Password doesnt match', () => {
    cy.get('#firstname').type('Kelompok')
    cy.get('#lastname').type('Dua')
    cy.get('#email_address').type('kelompok2@mail.com')
    cy.get('#password').type('Kelompok2')
    cy.get('#password-confirmation').type('Kelompok1')
    cy.get("button[title='Create an Account']").click()
    cy.get('#password-confirmation-error').should('contain','Please enter the same value again')
})
it('Failed Sign Up - Missing all required fields', () => {
  cy.get("button[title='Create an Account']").click()
  cy.get("#firstname-error").should("be.visible").and("contain", "This is a required field")
  cy.get("#lastname-error").should("be.visible").and("contain", "This is a required field")
  cy.get('#email_address-error').should("be.visible").and("contain", "This is a required field")
  cy.get("#password-error").should("be.visible").and("contain", "This is a required field")
})
})